version: '3.9'

services:
  water-intake-tracker-server-app:
    build: .
    container_name: water-intake-tracker-server-app
    depends_on:
      - water-intake-tracker-server-app-db-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@water-intake-tracker-server-app-db-service:5432/water_intake_tracker_server_app_db
      PYTHONPATH: ./src
    command: >
      sh -c "
        poetry run prisma migrate dev --name initial --schema=src/infrastructure/database/orm/prisma/schema.prisma &&
        poetry run prisma generate --schema=src/infrastructure/database/orm/prisma/schema.prisma &&
        poetry run uvicorn src.main:app_api --host 0.0.0.0 --port 8000 --reload --log-level debug
      "
    volumes:
      - .:/water-intake-tracker-server-app

  water-intake-tracker-server-app-db-service:
    image: postgres:15
    container_name: water-intake-tracker-server-app-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: water_intake_tracker_server_app_db
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
